# Generated by Django 5.2.5 on 2025-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
